/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hilltopperlib;

import org.junit.Test;

import static org.junit.Assert.*;

import com.team1732.autolib.Library;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
