/**
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.team1732.autolib;

import edu.wpi.first.wpilibj.Timer;

public class Library {
    public static Timer _stoppedTimer = new Timer();
    /**
     * This method simply returns true
     * 
     * @return true if this method is called
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
